"""블로그 주제 데이터. 주제 풀(카테고리별)과 재사용 시 적용할 관점(angle) 목록.

이 모듈은 순수 데이터만 담는다. 선택 로직은 picker.py, 슬러그 생성은 slugs.py.
"""

TOPIC_POOL: dict[str, list[str]] = {
    "Java/Spring": [
        "Spring Boot 3.x의 새로운 기능 완벽 가이드",
        "Java 21 Virtual Threads (Project Loom) 실전 적용",
        "GraalVM Native Image로 Spring Boot 앱 경량화하기",
        "Spring WebFlux와 리액티브 프로그래밍 패턴",
        "Spring Security 6.x OAuth2/OIDC 설정 가이드",
        "JPA N+1 문제 해결 완전 정복",
        "Spring Batch 5.x 대용량 데이터 처리 패턴",
        "Spring Data JPA Specification으로 동적 쿼리 작성",
        "Spring AOT와 프록시 없는 경량 컨텍스트",
        "Java Records와 Sealed Classes 모던 자바 문법",
        "Java의 Structured Concurrency 동시성 혁신",
        "Java 패턴 매칭과 Switch 표현식 완벽 이해",
        "Kotlin + Spring Boot 마이그레이션 실전 가이드",
        "Spring Modulith 모듈형 모놀리스 아키텍처",
        "R2DBC 반응형 데이터베이스 접근 전략",
        "Spring Boot DevTools와 LiveReload 개발 생산성 극대화",
        "Spring Integration 엔터프라이즈 통합 패턴 실전",
        "OpenAPI 3.0과 Spring REST Docs 문서화 전략",
        "Spring Cloud Gateway API 게이트웨이 구성하기",
        "Spring Boot Actuator와 Micrometer 모니터링 설정",
        "GraphQL과 Spring Boot API 설계 가이드",
        "Spring Boot 3 Native Test 지원 활용법",
        "Testcontainers로 Spring Boot 통합 테스트 환경 구축",
        "Spring Boot 트랜잭션 전파 옵션 완전 정리",
        "Spring Bean 생명주기와 초기화 순서 트러블슈팅",
        "Spring Boot Configuration Properties 검증과 타입-세이프 설정",
        "Java Garbage Collector 종류별 튜닝 전략 (G1, ZGC, Shenandoah)",
        "Spring Retry와 회복탄력성 패턴 구현",
        "Spring Boot 멀티모듈 프로젝트 구조 설계",
        "Spring AOP 프록시 내부 동작과 Self-Invocation 함정",
        "Spring Boot 커스텀 Actuator Endpoint 만들기",
        "Java Thread Pool 튜닝과 커넥션 풀 사이징 전략",
        "Spring Boot Bean Validation 커스텀 Validator 설계",
        "JVM 메모리 구조와 힙 덤프 분석 실전",
        "Java NIO와 논블로킹 I/O 내부 동작 원리",
        "Spring Cache 추상화와 캐시 무효화 전략",
        "Spring Event와 ApplicationEventPublisher 비동기 처리",
        "Lombok 사용의 함정과 대안 패턴",
        "MapStruct로 DTO 매핑 자동화하기",
        "Spring Boot 로깅 전략 Logback과 구조화 로그",
        "JPA 영속성 컨텍스트 동작 원리와 더티 체킹",
        "QueryDSL로 타입 세이프 쿼리 작성하기",
        "Spring Boot 애플리케이션 시작 시간 단축 기법",
        "Java 직렬화 취약점과 안전한 대안",
        "Spring WebClient 논블로킹 HTTP 클라이언트 실전",
        "Spring Boot 예외 처리 전략과 ControllerAdvice 설계",
    ],
    "서버/인프라": [
        "Kubernetes에서 Spring Boot 운영 베스트 프랙티스",
        "Docker 멀티스테이지 빌드로 이미지 사이즈 최적화",
        "Zero Downtime 배포 블루/그린 카나리 전략",
        "AWS ECS/Fargate Spring Boot 배포 전략",
        "서비스 메시 Istio와 Spring Boot 연동 가이드",
        "Nginx 리버스 프록시 고급 설정과 성능 튜닝",
        "Linux 서버 성능 분석과 병목 지점 찾기",
        "Helm Chart로 Kubernetes 애플리케이션 패키징",
        "Terraform으로 클라우드 인프라 코드화 (IaC)",
        "CI/CD 파이프라인 구축 GitHub Actions 완전 가이드",
        "HTTP/2와 HTTP/3 서버 설정 및 성능 비교",
        "gRPC와 Protocol Buffers 서버 간 통신 설계",
        "WebSocket과 STOMP 실시간 통신 서버 구현",
        "API Rate Limiting 전략과 구현 방법",
        "서버리스 아키텍처 AWS Lambda와 Spring Cloud Function",
        "Java Flight Recorder로 프로덕션 성능 분석하기",
        "ShedLock으로 분산 스케줄러 중복 실행 방지",
        "ELK 스택으로 Spring Boot 로그 중앙화",
        "Prometheus + Grafana Spring 앱 메트릭 시각화",
        "OpenTelemetry 분산 트레이싱 Spring Boot 적용",
        "Kubernetes HPA/VPA 오토스케일링 전략과 실전 튜닝",
        "컨테이너 리소스 Limit/Request 설정과 OOMKill 방지",
        "서비스 디스커버리 패턴 Consul vs Eureka 비교",
        "무중단 배포를 위한 Kubernetes Rolling Update 세부 튜닝",
        "Chaos Engineering 장애 주입 테스트 실전 가이드",
        "Envoy 데이터 플레인으로 서비스 메시 구성하기",
        "Kubernetes Operator 패턴으로 운영 자동화하기",
        "리눅스 cgroup과 컨테이너 격리 원리",
        "Kubernetes Ingress Controller 선택과 트래픽 라우팅",
        "Argo Rollouts 프로그레시브 딜리버리 구성",
        "HashiCorp Vault로 시크릿 관리 자동화하기",
        "Kubernetes StatefulSet과 상태 저장 워크로드 운영",
        "systemd 서비스 유닛 작성과 프로세스 관리",
        "Ansible로 서버 구성 관리 자동화",
        "S3 스토리지 클래스와 라이프사이클 비용 설계",
        "Kubernetes NetworkPolicy로 파드 간 트래픽 제어",
        "컨테이너 이미지 취약점 스캐닝 파이프라인 구축",
        "Kubernetes CSI 스토리지 프로비저닝 이해하기",
        "리눅스 파일 디스크립터와 ulimit 튜닝",
    ],
    "데이터베이스": [
        "PostgreSQL 쿼리 최적화와 인덱스 전략 완벽 가이드",
        "MySQL 파티셔닝과 샤딩 대규모 데이터 관리",
        "Redis를 활용한 분산 캐싱 전략과 패턴",
        "MongoDB Spring Data 반정형 데이터 처리 패턴",
        "Flyway로 데이터베이스 마이그레이션 자동화",
        "PostgreSQL MVCC와 트랜잭션 격리 수준 이해",
        "데이터베이스 커넥션 풀 HikariCP 최적화 가이드",
        "Apache Cassandra 분산 NoSQL 데이터 모델링",
        "Elasticsearch 풀텍스트 검색 엔진 구축하기",
        "TimescaleDB 시계열 데이터 저장과 분석",
        "데이터베이스 레플리케이션과 읽기 분산 전략",
        "Redis Pub/Sub과 Stream으로 실시간 메시징 구현",
        "CQRS 패턴 적용으로 읽기/쓰기 데이터베이스 분리",
        "DynamoDB 설계 원칙과 Single-Table Design",
        "ClickHouse 실시간 분석 쿼리 최적화 전략",
        "PostgreSQL Vacuum과 Bloat 관리 전략",
        "MySQL Replication Lag 원인 분석과 해결",
        "Redis Cluster 샤딩과 Failover 전략",
        "분산 락 Redisson vs ZooKeeper 비교",
        "무중단 데이터베이스 스키마 마이그레이션 전략",
        "OLTP와 OLAP 워크로드 분리 아키텍처",
        "PostgreSQL 파티션 테이블 설계와 운영",
        "인덱스 자료구조 B-Tree와 LSM-Tree 비교",
        "데이터베이스 데드락 원인 분석과 회피 전략",
        "Change Data Capture와 Debezium 실전 적용",
        "Redis 메모리 최적화와 만료 정책 설계",
        "쿼리 실행 계획 읽는 법 실전 가이드",
        "샤딩 키 선택 기준과 리샤딩 전략",
        "데이터베이스 백업과 시점 복구(PITR) 설계",
        "MySQL InnoDB 버퍼 풀 튜닝 전략",
        "이벤트 소싱 저장소 설계와 스냅샷 전략",
    ],
    "네트워크": [
        "TCP/IP 핵심 개념과 백엔드 개발자가 알아야 할 것들",
        "HTTP 캐싱 전략 Cache-Control 완전 정복",
        "DNS 동작 원리와 서비스 배포 시 고려사항",
        "TLS/SSL 인증서 원리와 HTTPS 설정 가이드",
        "로드 밸런서 L4 vs L7 차이와 선택 기준",
        "CDN 동작 원리와 글로벌 서비스 최적화 전략",
        "WebRTC 실시간 P2P 통신 백엔드 시그널링 서버",
        "OAuth 2.0과 OpenID Connect 인증 흐름 완전 이해",
        "mTLS 상호 인증과 서비스 간 보안 통신",
        "네트워크 패킷 분석 Wireshark 실전 활용법",
        "API Gateway 패턴과 서비스 라우팅 전략",
        "Long Polling vs SSE vs WebSocket 실시간 통신 비교",
        "QUIC 프로토콜과 HTTP/3의 등장 배경과 특징",
        "네트워크 파티션과 CAP 정리 실전 적용",
        "서비스 메시 사이드카 패턴과 mTLS 자동화",
        "API Gateway Rate Limiting 알고리즘 비교 (Token Bucket vs Sliding Window)",
        "gRPC 스트리밍 패턴과 백프레셔 처리",
        "TCP 혼잡 제어 알고리즘과 성능 영향",
        "Keep-Alive와 커넥션 재사용 최적화",
        "IPv6 전환과 백엔드 서비스 고려사항",
        "리버스 프록시 타임아웃 설정과 502 오류 진단",
        "CORS 동작 원리와 프리플라이트 요청 처리",
        "네트워크 지연 측정과 RTT 최적화 기법",
        "TLS 1.3 핸드셰이크 개선점과 성능",
        "BGP와 애니캐스트 기반 글로벌 트래픽 분산",
        "HTTP 헤더 압축 HPACK과 QPACK 동작 원리",
    ],
    "블록체인": [
        "블록체인 핵심 개념과 백엔드 개발자 관점에서의 이해",
        "스마트 컨트랙트 Solidity 개발 입문 가이드",
        "Web3.0과 탈중앙화 애플리케이션(dApp) 아키텍처",
        "NFT 기술 원리와 ERC-721 스마트 컨트랙트 구현",
        "DeFi(탈중앙화 금융) 핵심 프로토콜과 작동 원리",
        "이더리움 Layer 2 확장성 솔루션 비교 분석",
        "블록체인 지갑과 개인키 보안 관리 방법",
        "Hyperledger Fabric 기업용 블록체인 네트워크 구축",
        "IPFS 분산 파일 시스템과 블록체인 연동",
        "영지식 증명(ZKP) 개념과 프라이버시 보호 활용",
        "블록체인 오라클 문제와 Chainlink 솔루션",
        "DAO(탈중앙화 자율 조직) 거버넌스 설계 원리",
        "레이어2 롤업(Optimistic vs ZK) 기술 비교",
        "블록체인 트랜잭션 가스비 최적화 전략",
        "합의 알고리즘 PoW와 PoS 비교 분석",
        "스마트 컨트랙트 보안 취약점과 감사 방법",
        "이더리움 계정 추상화 ERC-4337 이해하기",
        "블록체인 노드 운영과 동기화 전략",
        "토큰 표준 ERC-20과 ERC-1155 비교",
        "크로스체인 브리지 동작 원리와 보안 위험",
        "온체인 데이터 인덱싱과 The Graph 활용",
        "스테이블코인 발행 구조와 담보 메커니즘",
    ],
    "최신 IT 기술 동향": [
        "LLM API 통합 백엔드 서비스 설계 패턴",
        "RAG(Retrieval-Augmented Generation) 시스템 구축하기",
        "AI 시대 개발자의 역할 변화와 생산성 향상 전략",
        "WebAssembly(WASM) 서버사이드 실행 가능성과 미래",
        "엣지 컴퓨팅과 CDN 엣지 함수 활용 전략",
        "FinOps 클라우드 비용 최적화와 엔지니어링",
        "플랫폼 엔지니어링과 Internal Developer Platform 구축",
        "GitOps 원칙과 ArgoCD를 통한 배포 자동화",
        "Feature Flag 기반 점진적 배포와 A/B 테스트",
        "SRE(사이트 신뢰성 엔지니어링) 핵심 원칙과 실천",
        "Rust 언어가 시스템 프로그래밍에서 주목받는 이유",
        "데이터 메시(Data Mesh) 아키텍처와 분산 데이터 관리",
        "Apache Kafka와 스트림 처리 실시간 데이터 파이프라인",
        "마이크로서비스 vs 모놀리스 선택 기준과 트레이드오프",
        "분산 트랜잭션 Saga 패턴과 이벤트 소싱 적용",
        "DDD 도메인 주도 설계 Spring Boot 실전 적용",
        "Hexagonal Architecture (포트와 어댑터) 패턴 실전",
        "Circuit Breaker 패턴과 Resilience4j 실전 가이드",
        "RabbitMQ vs Kafka 메시지 브로커 선택 가이드",
        "eBPF 리눅스 커널 관찰 가능성과 네트워크 보안",
        "JWT 토큰 보안 설계와 갱신 전략 완전 가이드",
        "API 보안 OWASP Top 10 취약점과 방어 전략",
        "Zero Trust 보안 모델과 백엔드 서비스 적용",
        "LLM 프롬프트 캐싱과 비용 최적화 전략",
        "벡터 데이터베이스 선택 기준과 성능 비교",
        "AI 에이전트 오케스트레이션 패턴 설계",
        "MLOps 파이프라인 구축과 모델 배포 전략",
        "이벤트 드리븐 아키텍처 Outbox 패턴 구현",
        "카나리 분석 자동화와 배포 안전장치",
        "함수형 프로그래밍 개념의 백엔드 적용",
        "모노레포 도입과 빌드 시스템 선택",
        "OpenTelemetry 로그 메트릭 트레이스 통합 전략",
        "테스트 피라미드와 계약 테스트 실전 적용",
        "백엔드 개발자를 위한 관찰 가능성 입문",
        "멀티테넌시 아키텍처 설계 패턴",
        "이벤트 스트리밍 기반 실시간 집계 설계",
        "API 버저닝 전략과 하위 호환성 관리",
        "코드 리뷰 문화와 리뷰 자동화 도구",
        "온콜 대응 체계와 인시던트 포스트모템 작성법",
    ],
}

# 주제를 모두 한 번씩 다룬 뒤, 같은 주제를 다른 시각으로 다시 쓰기 위한 관점 목록.
ANGLE_POOL: list[str] = [
    "아키텍처 설계와 트레이드오프",
    "성능 튜닝과 벤치마킹",
    "장애 대응과 트러블슈팅",
    "운영 및 모니터링 전략",
    "보안 및 규정 준수",
    "테스트 전략과 신뢰성 검증",
    "실전 마이그레이션 사례",
    "비용 최적화 관점",
]

ALL_TOPICS: list[tuple[str, str]] = [
    (category, topic)
    for category, topics in TOPIC_POOL.items()
    for topic in topics
]
